language: php
sudo: false
php:
  - 7.1
before_script:
  - composer self-update
  - composer update --prefer-source
  - composer install --dev --prefer-source
  - npm install -g grunt-cli
  - npm install
script: grunt travis
